### PR TITLE
adding darker background to tree views

### PR DESCRIPTION
**Pull request by simschla**
as such reduce the brightness on the screen
(inspired by vscode solarized theme)

before:
Screenshot 2019-07-30 at 17 11 03

after:
Screenshot 2019-07-30 at 17 10 20

### CODE REVIEW

**Comment by snowe2010** [comment]
Hmm. Kinda worried about this one, as the panes really clash now.

**Comment by simschla** [comment]
Totally understandable, as this comes down to taste;)

However, it looks way cleaner to me and it kind of elevates the editor part to the foreground while pushing the less important, noisy stuff to the background (navigators, outlines and the likes).

I also feel like it looks way less "clashy" when one looks at the whole workbench (not just the cutout from above):
Screenshot 2019-08-21 at 20 09 54

The idea to make the background of side-panels darker is taken directly from Visual Studio Code's default "solarized dark" theme:
Screenshot 2019-08-21 at 20 12 42

**Comment by snowe2010** [comment]
maybe if we changed the border pane color on top and bottom to match?

**Comment by simschla** [comment]
Something like this?

Screenshot 2019-08-24 at 10 16 25

Do you think this looks better?

(I did not find out how to style the toolbar within the panes, maybe you know how?)

**Comment by snowe2010** [comment]
Sorry, I've been extremely busy and also somewhat sick so I haven't had time to look at this. Let me see if I can dig up the toolbar key.

**Comment by simschla** [comment]
no worries. I'm very interested on how you go about to find out the necessary properties for the toolbar. To me it feels a lot like reverse engineering, sadly...

**Comment by snowe2010** [comment]
Of course, You can use the UI Inspector and Dropper, but they often do not work. You can also view the PSI Structure in that menu as well. Often I look at the JetBrains High Contrast theme because it changed almost every value and use that to figure out what to do. You can also use the UI Inspector to change the values on the fly and then you can find stuff pretty easily. A lot of it is guessing though :/

Screen Shot 2019-09-16 at 10 24 30 PM

**Comment by snowe2010** [comment]
Ok, so I just tried out the theme and I actually really like it how you have it. I'm going to go ahead and merge it. One thing I think we need to do with this change (in the future) is to remove the glaring white borders I added on stuff, as it really is not fitting with the dark panels. Looking at VS Code they did a really good job with the borders of stuff and I'd like to copy that.

**Comment by snowe2010** [comment]
Note, I have to deploy this stuff manually to JetBrains, so I will probably wait until your last PR is resolved and merged and then release.

**Pull request merged**
